sonar.host.url=http://20.55.80.124:9000
sonar.token=squ_8dfb87d68719e5051241b44ccc612b76c2fa21b8
sonar.login=admin
sonar.password=Slimnejmaoui2024*
sonar.projectKey=PFE
sonar.projectName=pfe1
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/**,src/assets/**,src/favicon.ico,src/environments/**,src/mocks/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.exclusions=**/node_modules/**,**/bower_components/**
sonar.typescript.tslint.reportPaths=lint-out-final.json
sonar.typescript.lcov.reportPaths=coverage/lcov.info



