apiVersion: apps/v1  # Pour Kubernetes v1.9 et plus
kind: Deployment
metadata:
  name: angular-k8s-deployment
spec:
  selector:
    matchLabels:
      app: angular-k8s-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: angular-k8s-deployment
    spec:
      containers:
        - name: angular-k8s-deployment
          image: nejmaoui/frontend:angular
          imagePullPolicy: Always
          env:
            - name: baseUrl
              valueFrom:
                configMapKeyRef:
                  name: service-spring
                  key: baseUrl
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-k8s-service
  labels:
    name: angular-k8s-deployment
spec:
  ports:
    - port: 80        # Port interne du service
      targetPort: 80   # Port du conteneur que l'application écoute
      protocol: TCP
  selector:
    app: angular-k8s-deployment
  type: LoadBalancer  # Remplace NodePort par LoadBalancer
